### ISSUE TITLE
Unable to deserialize calendar json for calendar

### ISSUE THREAD

**Issue by lawkaringithi** [jlinn/quartz-redis-jobstore#17]
I have created a calendar:

`HolidayCalendar holidayCalendar = new HolidayCalendar();`
`holidayCalendar.addExcludedDate(new DateTime().withDayOfMonth(28).toDate());`
`scheduler.addCalendar("myCalendar", holidayCalendar, false, false);`

when I try retrieving the calendar:
`scheduler.getCalendar("myCalendar");`

it throws the error:
`ERROR net.joelinn.quartz.jobstore.AbstractRedisStorage - Unable to deserialize calendar json for myCalendar`

This only happens when using redis as the JobStore. If I disable redis and use RAM instead, it works fine.

Any help on this?

Thanks.

**Comment by jlinn** [comment]
Thanks for reporting this.  I've released [v1.1.6](https://github.com/jlinn/quartz-redis-jobstore/releases/tag/quartz-redis-jobstore-1.1.6), which can properly serialize and deserialize HolidayCalendars.

**Comment by lawkaringithi** [comment]
Thanks, works great!
