### ISSUE TITLE
DisallowConcurrentExecution annotation not respected

### ISSUE THREAD

**Issue by soulrebel** [jlinn/quartz-redis-jobstore#18]
Hello,

it appears that `@DisallowConcurrentExecution` is not working. Can this be due to the storage backend or should I look for some other problem with my setup?

**Comment by jlinn** [comment]
Thanks for reporting this.  I've released [v1.1.7](https://github.com/jlinn/quartz-redis-jobstore/releases/tag/quartz-redis-jobstore-1.1.7), which should handle the `@DisallowConcurrentExecution` annotation properly.  Let me know if you run into any other issues.

**Comment by soulrebel** [comment]
Thank you very much! Seems to block correctly now. 
I had to clear the db though.
