### ISSUE TITLE
The job doesn't continue to work when another web app shut down

### ISSUE THREAD

**Issue by kenti-lan** [jlinn/quartz-redis-jobstore#20]
Hi,I run the web application on two tomcats base with the same redis config.
But when I shut down one tomcat which run the job,the another doesn't resume the job.
What's wrong with it?

**Comment by jlinn** [comment]
I created [a test](https://github.com/jlinn/quartz-redis-jobstore/blob/master/src/test/java/net/joelinn/quartz/MultiSchedulerIntegrationTest.java) to demonstrate proper operation of clustered schedulers.  Make sure that your schedulers aren't configured with the same name.

**Comment by kenti-lan** [comment]
Ok,thanks.

**Comment by kenti-lan** [comment]
I configed my SchedulerFactoryBean like below:
![qq 20161219154137](https://cloud.githubusercontent.com/assets/14138415/21304825/ba1e7cd6-c602-11e6-9073-010a1f83ca23.jpg)
I run two method on test, that will start up two spring context.
And the name of scheduler are all the same,'NON_CLUSTERED'.They even exec in the same time.
Should I post more detail about the config and code?

**Comment by jlinn** [comment]
Ah, ok.  You'll want to set the `org.quartz.scheduler.instanceId` config property to `AUTO`, and then optionally set a value for `org.quartz.scheduler.instanceIdGenerator.class`.  The default, `org.quartz.simpl.SimpleInstanceIdGenerator`, will work fine for development purposes.

**Comment by kenti-lan** [comment]
Ok,there is no help with that.
I ran the test to mock up the problem‘s environment.
![test](https://cloud.githubusercontent.com/assets/14138415/21307301/de96016c-c60f-11e6-8638-b624e35c114a.jpg)
Neither with old version nor the lastest one.
