### ISSUE TITLE
Need help with firing triggers

### ISSUE THREAD

**Issue by srbnyk** [jlinn/quartz-redis-jobstore#4]
Hi

I am trying to use this project to store some reminders in redis server. I am able to create the jobs and see them in redis, but the trigger I am creating is not being fired. Could you please help me with a sample, if possible?

Here is my code to initialize JobStore:
```java
        RedisJobStore jobStore = new RedisJobStore();
		jobStore.setHost("localhost");
		jobStore.setPort(6379);
		jobStore.setThreadPoolSize(10);
		try {
			jobStore.initialize(null, null);
			JobDetail job = JobBuilder.newJob(MyTestJob.class).withIdentity("my4_test_job").storeDurably(true).usingJobData("first_name", "Saurab").usingJobData("age", 23).usingJobData("last_name", "Nayak").build();
			CronTrigger trigger = TriggerBuilder.newTrigger().forJob(job).withSchedule(CronScheduleBuilder.dailyAtHourAndMinute(22, 18).inTimeZone(TimeZone.getTimeZone("IST")).withMisfireHandlingInstructionFireAndProceed()).withIdentity("my_test_job_trigger4").withDescription("sample trigger").build();
			jobStore.storeJobAndTrigger(job, (OperableTrigger) trigger);
			System.out.println();
		} catch (ObjectAlreadyExistsException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (JobPersistenceException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SchedulerConfigException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
```

Here is my Job Class:

```java
public class MyTestJob implements Job {
	private static String KEY_FIRST_NAME = "first_name";
	private static String KEY_LAST_NAME = "last_name";
	private static String KEY_AGE = "age";
	
	@Override
	public void execute(JobExecutionContext context)
			throws JobExecutionException {
		System.out.println(context.getJobDetail().getJobDataMap().getString(KEY_FIRST_NAME));
	}

}
```

I am not seeing the execute method being called. Please let me know if I have missed something here.

Thanks

**Comment by jlinn** [comment]
Typically, jobstores are configured via the [quartz.properties file](http://quartz-scheduler.org/generated/2.2.1/html/qs-all/#page/Quartz_Scheduler_Documentation_Set%2Fco_ins_configuring_quartz.html%23). Configuration options specific to the redis jobstore can be found [here](https://github.com/jlinn/quartz-redis-jobstore#configuration). 

Your job creation looks correct, but Quartz jobs are not usually stored in the jobstore directly.  Instead, use a scheduler, as shown [here](http://quartz-scheduler.org/generated/2.2.1/html/qs-all/#page/Quartz_Scheduler_Documentation_Set%2Fco_ins_starting_sample_app.html%23).
