### ISSUE TITLE
Is this project still maintained? 

### ISSUE THREAD

**Issue by mertkiray** [jlinn/quartz-redis-jobstore#48]
Is this project still maintained or not? If not what is the recommended way to integrate redis with quartz?

**Comment by mertkiray** [comment]
The maven dependency is not working
`<dependency>
    <groupId>net.joelinn</groupId>
    <artifactId>quartz-redis-jobstore</artifactId>
    <version>1.2.0</version>
</dependency>`

**Comment by ptahchiev** [comment]
That is because 1.2.0 was never released. Have a look here: https://github.com/jlinn/quartz-redis-jobstore/issues/43

**Comment by huangbotao** [comment]
> That is because 1.2.0 was never released. Have a look here: #43

@ptahchiev  hi, do you have the same problem: when add job will hung for a long time, in twenty thousands of jobs?

hope your reply！
