### ISSUE TITLE
Releasing Triggers

### ISSUE THREAD

**Issue by namack75** [jlinn/quartz-redis-jobstore#7]
Hi,

Just a question, was there a reason why a previously acquired trigger is not release, when a newer trigger is acquired?

Noticing the following case:
1) Trigger1 to fire in 20s, Trigger1 acquired.
2) Trigger2 to fire in 10s, Trigger2 acquired.
3) Trigger2 fired.
4) x time later (after the defined Trigger1 fire time), Trigger1 is acquired as a MisFire.

Thanks

**Comment by jlinn** [comment]
That would appear to be a bug.  [This](https://github.com/jlinn/quartz-redis-jobstore/commit/102be930f50dad839f39213e9a07b1da50410f79) should fix that.  Thanks for pointing it out!

**Comment by namack75** [comment]
Awesome. Thanks for the quick fix.
